// client-vue3/src/components/TransactionTable.vue
<script setup>
import { transactionsStore } from '../stores/transactionsStore.js'
import _ from 'lodash'
import { computed, onMounted, ref, watch } from 'vue'
import { DateTime } from 'luxon'

const store = transactionsStore()
let iRowActive = ref(0)

const filteredRows = computed(() => {
  if (!store.filterCategory) {
    return store.rows
  }
  let rows = _.filter(store.rows, (r) => _.last(r) === store.filterCategory)
  if (store.filterCategory === 'X') {
    const emptyRows = _.filter(store.rows, (r) => !_.last(r))
    rows = _.concat(rows, emptyRows)
  }
  return rows
})

onMounted(async () => {
  document.addEventListener('keydown', onKeydown)
})

watch(
  () => store.clickTransaction,
  () => {
    const time = store.clickTransaction.time
    const category = store.clickTransaction.category
    const rows = filteredRows.value
    for (let i = 0; i < rows.length; i += 1) {
      const row = rows[i]
      if (time === row[1] && category === _.last(row)) {
        const targetId = row[0]
        document.getElementById(targetId).scrollIntoView()
        iRowActive.value = i
      }
    }
  }
)

async function onKeydown(event) {
  if (store.keyLock) {
    return
  }
  if (event.key === 'ArrowDown') {
    iRowActive.value += 1
    if (iRowActive.value === store.rows.length) {
      iRowActive.value = 0
    }
  } else if (event.key === 'ArrowUp') {
    iRowActive.value -= 1
    if (iRowActive.value < 0) {
      iRowActive.value = store.rows.length - 1
    }
  } else {
    let category = event.key.toUpperCase()
    if (_.find(store.categories, (c) => c.key === category)) {
      const id = filteredRows.value[iRowActive.value][0]
      await store.updateCategory(id, category)
    }
  }
}

function formatRow(row) {
  let result = _.cloneDeep(row)
  for (let iCol = 0; iCol < row.length; iCol += 1) {
    const header = store.headers[iCol]
    if (header && header.indexOf('date') >= 0) {
      result[iCol] = DateTime.fromISO(result[iCol]).toFormat('ddLLLyy')
    }
  }
  return result
}
</script>

<style scoped>
th,
td {
  text-align: left;
}
.active {
  background-color: #ffe;
}
</style>

<template>
  <table class="table">
    <thead>
      <tr>
        <th scope="col" v-for="key of store.headers" :key="key">{{ key }}</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(row, iRow) of filteredRows" :key="row[0]" :id="row[0]" @click="iRowActive = iRow">
        <td
          v-for="(val, i) of formatRow(row)"
          :class="iRow === iRowActive ? 'active' : ''"
          :key="i"
        >
          <div v-if="i < row.length - 1">
            {{ val }}
          </div>
          <template v-else>
            <select
              class="form-select"
              aria-label="Default select example"
              @change="(e) => store.updateCategory(row[0], e.target.value)"
              @focus="iRowActive = iRow"
            >
              <option selected :value="null">-- select an option --</option>
              <option
                v-for="c of store.categories"
                :key="c.key"
                :value="c.key"
                :selected="c.key === _.last(row)"
              >
                {{ c.key + ' - ' + c.desc }}
              </option>
            </select>
          </template>
        </td>
      </tr>
    </tbody>
  </table>
</template>

// client-react/src/features/TransactionTable.tsx
import { useEffect, useRef, useState } from 'react'
import { useSelector } from 'react-redux'
import { IRootState, updateCategory } from '../store'
import _ from 'lodash'
import { DateTime } from 'luxon'

export default function TransactionTable() {
    const [iRowActive, _setIRowActive] = useState<number>(0)
    const transactions = useSelector((state: IRootState) => state.transactions)
    const nCol = transactions.headers.length
    const iColLast = nCol - 1

    const iRowActiveRef = useRef(iRowActive)

    function setIRowActive(i: number) {
        iRowActiveRef.current = i
        _setIRowActive(i)
    }

    let rows = transactions.rows
    if (transactions.filterCategory) {
        rows = _.filter(
            rows,
            (row) => _.last(row) === transactions.filterCategory
        )
    }

    function gotoIRow(iRow: number) {
        const div = document.getElementById(rows[iRow][0])
        if (div) {
            div.scrollIntoView()
        }
    }

    useEffect(() => {
        if (transactions.clickTransaction) {
            const time = transactions.clickTransaction.time
            const category = transactions.clickTransaction.category

            for (let i = 0; i < rows.length; i += 1) {
                const row = rows[i]
                if (time === row[1] && category === _.last(row)) {
                    gotoIRow(i)
                    setIRowActive(i)
                }
            }
        }
    }, [transactions.clickTransaction])

    useEffect(() => {
        document.addEventListener('keydown', onKeydown)
        return () => {
            document.removeEventListener('keydown', onKeydown)
        }
    })

    async function onKeydown(event: KeyboardEvent) {
        const iRow = iRowActiveRef.current
        if (transactions.keyLock) {
            return
        }
        if (event.key === 'ArrowDown') {
            if (iRow === rows.length - 1) {
                setIRowActive(0)
            } else {
                setIRowActive(iRow + 1)
            }
        } else if (event.key === 'ArrowUp') {
            if (iRow === 0) {
                setIRowActive(rows.length - 1)
            } else {
                setIRowActive(iRow - 1)
            }
        } else {
            const category = event.key.toUpperCase()
            if (_.find(transactions.categories, (c) => c.key === category)) {
                const id = rows[iRowActive][0]
                await updateCategory(id, category)
            }
        }
    }

    function formatValue(row: string[], iCol: number, id: string) {
        const val = row[iCol]
        if (iCol === 1) {
            return DateTime.fromISO(val).toFormat('ddLLLyy')
        }
        if (iCol !== iColLast) {
            return val
        }
        const options = [
            { key: '', desc: '-- select an option --' },
            ...transactions.categories.map((c) => ({
                key: c.key,
                desc: `${c.key} - ${c.desc}`,
            })),
        ]
        return (
            <select
                className="form-select"
                value={val ? val : ''}
                onChange={(e) => updateCategory(id, e.target.value)}
            >
                {options.map(({ key, desc }) => (
                    <option value={key} key={key}>
                        {desc}
                    </option>
                ))}
            </select>
        )
    }

    function rowStyle(iRow: number) {
        return iRow === iRowActive ? { backgroundColor: '#ffe' } : {}
    }

    return (
        <table className="table">
            <thead>
                <tr>
                    {transactions.headers.map((k) => (
                        <th key={k}>{k}</th>
                    ))}
                </tr>
            </thead>
            <tbody>
                {rows.map((row, iRow) => (
                    <tr
                        id={row[0]}
                        key={row[0]}
                        onClick={() => setIRowActive(iRow)}
                    >
                        {_.range(0, nCol).map((iCol) => (
                            <td style={rowStyle(iRow)} key={iCol}>
                                {formatValue(row, iCol, row[0])}
                            </td>
                        ))}
                    </tr>
                ))}
            </tbody>
        </table>
    )
}
