// client-vue3/src/components/DataTable.vue
<script setup>
import { transactionsStore } from '../stores/transactionsStore.js'
import _ from 'lodash'
import { remote } from '../../../rpc/rpc.js'
import { computed, onMounted, ref, watch } from 'vue'
import { DateTime } from 'luxon'

const store = transactionsStore()
let descByCategory = {}
let categoryKeys = []
let iRowActive = ref(0)

onMounted(async () => {
  await store.loadCategories()
  descByCategory = {}
  categoryKeys = []
  for (let category of store.categories) {
    descByCategory[category.key] = category.desc
    categoryKeys.push(category.key)
  }
  document.addEventListener('keydown', onKeydown)
})

watch(
  () => store.clickTransaction,
  () => {
    const time = store.clickTransaction.time
    const category = store.clickTransaction.category
    const rows = filteredRows.value
    for (let i = 0; i < rows.length; i += 1) {
      const row = rows[i]
      if (time === row[1] && category === _.last(row)) {
        const targetId = row[0]
        document.getElementById(targetId).scrollIntoView()
        iRowActive.value = i
      }
    }
  }
)

const filteredRows = computed(() => {
  if (!store.filterCategory) {
    return store.rows
  }
  let rows = _.filter(store.rows, (r) => _.last(r) === store.filterCategory)
  if (store.filterCategory === 'X') {
    const emptyRows = _.filter(store.rows, (r) => !_.last(r))
    rows = _.concat(rows, emptyRows)
  }
  return rows
})

function getRow(iRow) {
  return _.cloneDeep(filteredRows.value[iRow])
}

function selectRow(iRow) {
  iRowActive.value = iRow
}

async function setCategory(iRow, category) {
  console.log('setCategory', iRow, category)
  let row = getRow(iRow)
  let id = row[0]
  let iLast = row.length - 1
  row[iLast] = category
  store.updateRow(row)
  await remote.update_transactions(store.table, id, { category })
}

async function onKeydown(event) {
  if (store.keyLock) {
    return
  }
  if (event.key === 'ArrowDown') {
    iRowActive.value += 1
    if (iRowActive.value === store.rows.length) {
      iRowActive.value = 0
    }
  } else if (event.key === 'ArrowUp') {
    iRowActive.value -= 1
    if (iRowActive.value < 0) {
      iRowActive.value = store.rows.length - 1
    }
  } else {
    let category = event.key.toUpperCase()
    if (categoryKeys.includes(category)) {
      await setCategory(iRowActive.value, category)
    }
  }
}

function displayCategory(v) {
  return v + ' - ' + descByCategory[v]
}

function formatRow(row) {
  let result = _.cloneDeep(row)
  for (let iCol = 0; iCol < row.length; iCol += 1) {
    const header = store.headers[iCol]
    if (header && header.indexOf('date') >= 0) {
      const date = DateTime.fromISO(result[iCol])
      result[iCol] = date.toFormat('ddLLLyy')
    }
  }
  return result
}
</script>

<style scoped>
th,
td {
  text-align: left;
}

.active {
  background-color: #ffe;
}
</style>

<template>
  <table class="table">
    <thead>
      <tr>
        <th scope="col" v-for="key of store.headers" :key="key">{{ key }}</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="(row, iRow) of filteredRows" :key="row[0]" :id="row[0]" @click="iRowActive = iRow">
        <td
          v-for="(val, i) of formatRow(row)"
          v-bind:class="iRow === iRowActive ? 'active align-middle' : 'align-middle'"
          :key="i"
        >
          <div v-if="i < row.length - 1">
            {{ val }}
          </div>
          <template v-else>
            <select
              class="form-select"
              aria-label="Default select example"
              @change="(e) => setCategory(iRow, e.target.value)"
              @focus="selectRow(iRow)"
            >
              <option selected :value="null">-- select an option --</option>
              <option
                v-for="c of store.categories"
                :key="c.key"
                :value="c.key"
                :selected="c.key === _.last(row)"
              >
                {{ displayCategory(c.key) }}
              </option>
            </select>
          </template>
        </td>
      </tr>
    </tbody>
  </table>
</template>

// client-svelte/src/routes/table/[table]/DataTable.svelte
<script>
	import {remote} from '../../../../../rpc/rpc.js';
	import {onMount} from 'svelte';
	import {categories, clickTransaction, filterCategory, headers, keyLock, rows, table} from '../../../store.js';
	import _ from 'lodash';

	let iRowActive = 0;
    $: filteredRows = displayRows($rows, $filterCategory);
    $: dummy = newClick(filteredRows, $clickTransaction);


    function newClick(rows, transaction) {
        if (!transaction) {
            return;
        }
        for (let i = 0; i < rows.length; i += 1) {
            const row = rows[i];
            if (transaction.time === row[1] && transaction.category === _.last(row)) {
                console.log('goto', row[0], transaction);
                document.getElementById(row[0]).scrollIntoView();
                iRowActive = i;
                return;
            }
        }
    }

    /**
     * @param  {(string|number)[]} rows
     * @param  {string} filterCategory
     */
    function displayRows(rows, filterCategory) {
        console.log('displayRows', clickTransaction);
        if (!filterCategory) {
            return rows;
        }
        rows = _.filter(rows, (r) => _.last(r) === filterCategory);
        if (filterCategory === 'X') {
            const emptyRows = _.filter(rows, (r) => !_.last(r));
            rows = _.concat(rows, emptyRows);
        }
        return rows;
    }

    /**
     * @param  {number} iRow
     * @param  {string} category
     */
    async function setCategory(iRow, category) {
        let filteredRow = filteredRows[iRow];
        let id = filteredRow[0];
        let row = _.find($rows, (r) => r[0] === id);
        let iLast = row.length - 1;
        row[iLast] = category;
        $rows = $rows;
        await remote.update_transactions($table, id, {category});
    }

    async function onKeydown(event) {
        if ($keyLock) {
            return;
        }
        const rows = filteredRows;
        if (event.key === 'ArrowDown') {
            iRowActive += 1;
            if (iRowActive === rows.length) {
                iRowActive = 0;
            }
        } else if (event.key === 'ArrowUp') {
            iRowActive -= 1;
            if (iRowActive < 0) {
                iRowActive = rows.length - 1;
            }
        } else {
            let category = event.key.toUpperCase();
            if (_.find($categories, (c) => c.key === category)) {
                await setCategory(iRowActive, category);
            }
        }
    }

    function clickRow(iRow) {
        iRowActive = iRow;
    }

    onMount(() => {
        document.addEventListener('keydown', onKeydown);
    });
</script>

<table class="table">
    <thead>
    {#each $headers as header}
        <th scope="col">{header}</th>
    {/each}
    </thead>
    <tbody>
    {#each filteredRows as row, iRow}
        <tr id={row[0]} on:click={(e) => clickRow(iRow)}>
            {#each row as val, iCol}
                <td style={iRow === iRowActive ? 'background-color: #ffe;' : ''}>
                    {#if iCol < row.length - 1}
                        {val}
                    {:else}
                        <select
                                class="form-select"
                                bind:value={row[iCol]}
                                aria-label="Default select example"
                                on:change={(e) => setCategory(iRow, e.target.value)}
                        >
                            <option disabled selected value> -- select an option --</option>
                            {#each $categories as c}
                                <option value={c.key}>
                                    {c.key + ' - ' + c.desc}
                                </option>
                            {/each}
                        </select>
                    {/if}
                </td>
            {/each}
        </tr>
    {/each}
    </tbody>
</table>
